from django.conf.urls import include, url
from rest_framework_jwt.views import obtain_jwt_token

from user_management.views import UsersViewset
from  user_management.utils import CustomReadOnlyRouter, SimpleRouter

router = CustomReadOnlyRouter()
router.register(prefix = r'users', viewset = UsersViewset, base_name = "users1")

urlpatterns = [
    url(r'^', include(router.urls)),  # will include url generated by router
    url(r'^login/', obtain_jwt_token),
]