# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-07 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('firstname', models.CharField(default='N/A', max_length=100)),
                ('lastname', models.CharField(default='N/A', max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
