# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-08 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20180407_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='designation',
            field=models.CharField(choices=[(b'ADMIN', b'ADMIN'), (b'STAFF', b'STAFF')], default='STAFF', max_length=10),
        ),
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='firstname',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastname',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
