# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-08 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20180408_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
    ]
